### ISSUE TITLE
Remove or update WC-End2End paper

### ISSUE THREAD

**Issue by fdedden** [Copilot-Language/copilot-discussion#27]
The documentation at https://github.com/Copilot-Language/copilot-discussion/tree/master/WC-End2End is incomplete. We should either remove it, or find the original sources.

**Comment by GAJaloyan** [comment]
The documentation was an unfinished attempt at rewriting the report located in:
copilot-discussion/GAJaloyan/sample_report/
I think it can be safely removed from the repo.
