### ISSUE TITLE
tutorial: Update explanations of C code generated

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/copilot-discussion#31]
**Description**

Copilot 3.12 now generates an additional header file with struct definitions. Any references in the tutorial to the C files generated should be updated.

**Type**

- Bug: keep up-to-date with changes in Copilot.

**Additional context**

- https://github.com/Copilot-Language/copilot/issues/373

**Requester**

- Ivan Perez

**Method to check presence of the issue**

The description of the C files generated does not mention the `<prefix>_types.h` that is also generated. This file is generated in Copilot 3.12.

**Expected result**

Any mentions of the C code generated that explicitly mention and/or describe the files should also mention the `<prefix>_types.h` file that contains struct definitions.

**Desired result**

Any mentions of the C code generated that explicitly mention and/or describe the files should also mention the `<prefix>_types.h` file that contains struct definitions.

**Proposed solution**

Modify mentions of the C code generated that explicitly mention and/or describe the files generated to also mention the `<prefix>_types.h` file that contains struct definitions.

**Further notes**

None.

**Comment by ivanperez-keera** [comment]
Change Manager: Confirmed that the issue exists.

**Comment by ivanperez-keera** [comment]
Technical Lead: Confirmed that the issue should be addressed.

**Comment by ivanperez-keera** [comment]
Technical Lead: Issue scheduled for fixing in Copilot 3.13.

Fix assigned to: @willpog

**Comment by willpog** [comment]
Implementor: Solution implemented review requested.

**Comment by ivanperez-keera** [comment]
Change Manager: Verified that:

Solution is implemented:
-  [X] The code proposed compiles and passes all tests. Details:
    Checked that tex compiles correctly.
- [X] The solution proposed produces the expected result. Details:
    Manually inspected tutorial and changes.
- [X] Change history is clear.
- [X] Commit messages are clear.

**Comment by ivanperez-keera** [comment]
Change Manager: Change ready to be merged.
