### ISSUE TITLE
tutorial: Update authors and emails

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/copilot-discussion#32]
**Description**

The tutorial has an outdated list of contributors, and emails. That list should be updated to reflect any new co-authors, and the emails updated or removed.

**Type**

- Management: update author / email list.

**Additional context**

None

**Requester**

- Alwyn Goodloe

**Method to check presence of the issue**

Author list does not contain Will Pogge (who should be listed), and Ivan Perez' email is outdated.

**Expected result**

Author list should also incode Will Pogge. Emails shown should be updated and contain only Alwyn, Frank, Will and Ivan.

**Desired result**

Author list should also incode Will Pogge. Emails shown should be updated and contain only Alwyn, Frank, Will and Ivan.

**Proposed solution**

- Update author list to include Will Pogge.
- Remove emails of all authors except for Alwyn, Frank, Will and Ivan.
- Update emails of Alwyn, Frank, Will and Ivan as needed.

**Further notes**

None.

**Comment by ivanperez-keera** [comment]
Change Manager: Confirmed that the issue exists.

**Comment by ivanperez-keera** [comment]
Technical Lead: Confirmed that the issue should be addressed.

**Comment by ivanperez-keera** [comment]
Technical Lead: Issue scheduled for fixing in Copilot 3.13.

Fix assigned to: @willpog

**Comment by willpog** [comment]
Implementor: Solution implemented review requested.

**Comment by ivanperez-keera** [comment]
Change Manager: Verified that:

Solution is implemented:
-  [X] The code proposed compiles and passes all tests. Details:
    Checked that tex compiles correctly.
- [X] The solution proposed produces the expected result. Details:
    Manually inspected tutorial and changes.
- [X] Change history is clear.
- [X] Commit messages are clear.

**Comment by ivanperez-keera** [comment]
Change Manager: Change ready to be merged.
